name: test-webhook
on: workflow_dispatch
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X POST ${{ secrets.DISCORD_WEBHOOK }} \
            -H "Content-Type: application/json" \
            -d '{"content":"🧪 Webhook test from GitHub Actions"}'
